<a href="https://colab.research.google.com/github/oscarserc/github-slideshow/blob/master/PRUEBA_SuccessorRepresentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Prueba con las matrices y el aprendizaje**

In [9]:
import numpy as np

# Fijando los valores de los parámetros
action_size = 3
state_size  = 6

M = np.stack([np.identity(state_size) for i in range(action_size)])
M

array([[[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]],

       [[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]],

       [[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]]])

In [14]:
M[0,:,:] = M[0,:,:]*2
M[0]

array([[16.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 16.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 16.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 16.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 16.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 16.]])

In [15]:

# Del conjunto de 3 matrices que tenemos
# seleccionamos: FILA (s=2) y 
# TODAS LAS COLUMNAS
estado = 2

M[:,estado,:]


array([[ 0.,  0., 16.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.]])

## **Hacemos algunas pruebas con la librería: UTILS**

In [ ]:
# NO VIENE INSTALADO DE SERIE
!pip install utils

In [21]:
import utils

estado = 2

#objetivo = utils.onehot(estado, state_size)
#objetivo
objetivo = [0,0,1,0,0,0]

np.matmul(M[:,estado,:], objetivo)


array([16.,  1.,  1.])